# -----------------------------
# Database Configuration
# -----------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/plasign3d
spring.datasource.username=root
spring.datasource.password=Mercy@2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# -----------------------------
# Server Port
# -----------------------------
server.port=8081

# -----------------------------
# File Upload Configuration
# -----------------------------
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.location=${user.dir}/uploads
